pipeline {
    agent any

    stages {
        stage('Execute Unit Tests'){
            parallel{
                        stage('[Unit Tests] [Backend]') {
                            agent {
                                docker {
                                    image 'snakee/golang-junit:1.21'
                                    reuseNode true
                                }
                            }
                            steps {
                                dir('bugtracker-backend'){
                                    // We also explicitly point the Go cache into the workspace
                                    withEnv([
                                                /*
                                                These are environment variables specific to the Go programming language (Golang) that tell the Go toolchain where to store certain types of files.
                                                GOPATH is the primary directory where Go stores downloaded third-party dependencies.
                                                GOCACHE is the directory where Go stores recently compiled build outputs.
                                                */
                                                "GOCACHE=${WORKSPACE}/.cache/go-build",
                                                "GOPATH=${WORKSPACE}/.go"
                                            ])
                                    {
                                        sh  '''
                                                go test -v ./... 2>&1 | go-junit-report > test-results.xml

                                                # Generate Coverage Report
                                                go test -coverprofile=coverage.out -covermode=atomic ./...
                                                go tool cover -html=coverage.out -o  coverage.html

                                                mkdir -p reports
                                                mv coverage.html reports/
                                            '''
                                    }
                                }
                            }
                            post {
                                always {
                                    junit 'bugtracker-backend/test-results.xml'
                                    publishHTML target: [
                                        reportDir: 'bugtracker-backend/reports',
                                        reportFiles: 'coverage.html',
                                        reportName: 'Backend Coverage Report'
                                    ]
                                }
                            }
                        }
                        stage('[Unit Tests] [Frontend]') {
                            agent{
                                docker{
                                    image 'node:20-alpine'
                                    reuseNode true
                                }
                            }
                            steps {
                                dir('bugtracker-frontend'){
                                    sh '''
                                            npm ci
                                            npm test

                                            mkdir -p reports
                                            mv coverage reports/
                                    '''
                                }
                            }
                            post {
                                always {
                                    junit 'bugtracker-frontend/test-results.xml'
                                    publishHTML target: [
                                        reportDir: 'bugtracker-frontend/reports/coverage',
                                        reportFiles: 'index.html',
                                        reportName: 'Frontend Coverage Report'
                                    ]
                                }
                            }
                        }
                }
        }
        stage('Launch App'){
            agent {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                    sh 'docker compose up --build -d'
                }
        }
        stage('API Tests'){
            agent {
                docker{
                    image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps {
                dir('tests-api'){
                    /*
                        wait-port: This is a handy Node.js utility. It pauses the pipeline and constantly checks (polls) the specified URL or port until it becomes available.
                        npx: This tells npm to execute the wait-port package directly from the npm registry without needing to install it globally first.
                        If your tests start immediately, they will fail because the server isn't ready yet. This command ensures the pipeline waits exactly until the backend is fully up and running before moving on to the next step.
                    */
                    sh 'npx wait-port http://localhost:8080/api/health -t 30000'
                    sh 'npm ci'
                    sh 'npx playwright test'
                }
            }
            post {
                always {
                    junit 'tests-api/test-results/results.xml'
                    publishHTML target: [
                        reportDir: 'tests-api/playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'API Tests Report'
                    ]
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}