pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'echo "Hello Jenkins" '
                sh 'date'
                sh 'pwd'
                sh 'whoami'
                sh 'cat /etc/os-release'
            }
        }
    }
}