pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    args '-e GOCACHE=${WORKSPACE}/.cache'
                }
            }
            steps {
                echo 'Hello World'
                dir('bugtracker-backend'){
                    sh 'mkdir -p ${WORKSPACE}/.cache'
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
